import { createHash, randomUUID } from 'node:crypto'
import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { HIVE_DIR_NAME } from './tasks-file.js'
import type { DreamRunRecord } from './team-memory-dream-store.js'
import type { MemoryEntryWithSources } from './team-memory-store.js'

export const MEMORY_FILE_NAME = 'memory.md'
export const MEMORY_RELATIVE_PATH = `${HIVE_DIR_NAME}/${MEMORY_FILE_NAME}`
export const MEMORY_EXPORT_DEBOUNCE_MS = 2000
export const MEMORY_EXPORT_DREAM_CHANGELOG_LIMIT = 10

const GENERATED_MARKER = '<!-- hive-memory:generated v1'
const GENERATED_END_MARKER = '<!-- /hive-memory:generated -->'
const GENERATED_WARNING =
  'Generated by Hive from SQLite. Do not edit this file by hand; user edits are backed up before regeneration.'

const KIND_TITLES: Record<MemoryEntryWithSources['kind'], string> = {
  decision: 'Decisions',
  fact: 'Facts',
  pitfall: 'Pitfalls',
  preference: 'Preferences',
  procedure_ref: 'Procedure refs',
}

export const getMemoryFilePath = (workspacePath: string) =>
  join(workspacePath, HIVE_DIR_NAME, MEMORY_FILE_NAME)

const hashText = (text: string) => createHash('sha256').update(text).digest('hex')

const writeUtf8FileAtomically = (targetPath: string, content: string) => {
  const tempPath = join(dirname(targetPath), `.${basename(targetPath)}.${randomUUID()}.tmp`)
  let committed = false
  let fd: number | null = null
  try {
    try {
      fd = openSync(tempPath, 'w')
      writeFileSync(fd, content, 'utf8')
      fsyncSync(fd)
    } finally {
      if (fd !== null) {
        closeSync(fd)
        fd = null
      }
    }
    renameSync(tempPath, targetPath)
    committed = true
  } finally {
    if (!committed && existsSync(tempPath)) rmSync(tempPath, { force: true })
  }
}

const normalizeInline = (value: string) => value.replace(/\s+/g, ' ').trim()

const formatBody = (body: string) =>
  body
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .split('\n')
    .map((line, index) => (index === 0 ? normalizeInline(line) : `  ${line.trim()}`))
    .join('\n')

const formatEntryLine = (entry: MemoryEntryWithSources) => {
  const labels: string[] = [entry.kind]
  if (entry.pinned) labels.push('pinned')
  if (entry.disabled) labels.push('disabled')
  if (entry.scope === 'user') labels.push('scope: user')
  if (entry.procedureRef) {
    labels.push(`ref: ${entry.procedureRef.type}:${entry.procedureRef.id}`)
    if (entry.procedureRef.title) labels.push(`ref_title: ${entry.procedureRef.title}`)
  }
  labels.push(`source: ${entry.source}`)
  const source = entry.sources[0]
  if (source?.actorNameSnapshot) labels.push(`from: ${source.actorNameSnapshot}`)
  if (entry.tags.length > 0) labels.push(`tags: ${entry.tags.join(', ')}`)
  return `- [${labels.join(', ')}] ${formatBody(entry.body)}`
}

const formatDreamRunLine = (run: DreamRunRecord) => {
  const report = run.report
  const counts = report
    ? [
        `${report.added.length} added`,
        `${report.rewritten.length} rewritten`,
        `${report.archived.length} archived`,
        `${report.merged.length} merged`,
      ].join(', ')
    : run.error
      ? `error: ${normalizeInline(run.error)}`
      : 'no report'
  const finished = run.finishedAt ? new Date(run.finishedAt).toISOString() : 'running'
  const window =
    run.inputSeqFrom === null || run.inputSeqTo === null
      ? 'no input'
      : `seq ${run.inputSeqFrom}-${run.inputSeqTo}`
  return `- [${run.status}, ${run.trigger}, ${finished}, ${window}] ${counts}`
}

const renderDreamChangelog = (dreamRuns: DreamRunRecord[]) => {
  if (dreamRuns.length === 0) return ['## Dream changelog', 'No dream runs yet.', '']
  return ['## Dream changelog', ...dreamRuns.map(formatDreamRunLine), '']
}

const renderMemoryBody = (entries: MemoryEntryWithSources[], dreamRuns: DreamRunRecord[]) => {
  const activeEntries = entries.filter((entry) => entry.status === 'active')
  const lines: string[] = []
  if (activeEntries.length === 0) {
    lines.push('No active memory entries.', '')
  } else {
    for (const kind of Object.keys(KIND_TITLES) as Array<MemoryEntryWithSources['kind']>) {
      const group = activeEntries.filter((entry) => entry.kind === kind)
      if (group.length === 0) continue
      lines.push(`## ${KIND_TITLES[kind]}`)
      for (const entry of group) lines.push(formatEntryLine(entry))
      lines.push('')
    }
  }
  lines.push(...renderDreamChangelog(dreamRuns))
  return lines.join('\n')
}

export const renderMemoryExport = (
  entries: MemoryEntryWithSources[],
  dreamRuns: DreamRunRecord[] = []
) => {
  const body = renderMemoryBody(entries, dreamRuns)
  return `${renderGeneratedPrefix(hashText(body))}${body}`
}

const renderGeneratedPrefix = (hash: string) =>
  `${[
    '# Hive Memory',
    '',
    `${GENERATED_MARKER} sha256=${hash} -->`,
    GENERATED_WARNING,
    GENERATED_END_MARKER,
    '',
  ].join('\n')}\n`

const parseGeneratedBody = (content: string) => {
  const markerMatch = content.match(/<!-- hive-memory:generated v1 sha256=([a-f0-9]+) -->/u)
  const endIndex = content.indexOf(GENERATED_END_MARKER)
  if (!markerMatch?.[1] || endIndex === -1) return null
  const bodyStart = endIndex + GENERATED_END_MARKER.length
  return {
    body: content.slice(bodyStart).replace(/^\n+/, ''),
    hash: markerMatch[1],
  }
}

const shouldBackupExisting = (content: string) => {
  if (!content.includes(GENERATED_MARKER)) return true
  const generated = parseGeneratedBody(content)
  if (!generated) return true
  if (content !== `${renderGeneratedPrefix(generated.hash)}${generated.body}`) return true
  return hashText(generated.body) !== generated.hash
}

const backupExistingIfNeeded = (targetPath: string, now: () => number) => {
  if (!existsSync(targetPath)) return
  const existing = readFileSync(targetPath, 'utf8')
  if (!shouldBackupExisting(existing)) return
  const backupPath = `${targetPath}.backup-${now()}-${randomUUID()}`
  writeUtf8FileAtomically(backupPath, existing)
}

export interface TeamMemoryExportService {
  cancel: (workspaceId: string) => void
  close: () => Promise<void>
  flush: (workspaceId: string) => Promise<void>
  schedule: (workspaceId: string) => void
}

export const createTeamMemoryExportService = ({
  debounceMs = MEMORY_EXPORT_DEBOUNCE_MS,
  getWorkspacePath,
  listDreamRuns = () => [],
  listEntries,
  logError = (workspaceId, error) =>
    console.error(`[hive] failed to export memory for workspace ${workspaceId}`, error),
  now = () => Date.now(),
}: {
  debounceMs?: number
  getWorkspacePath: (workspaceId: string) => string
  listDreamRuns?: (workspaceId: string) => DreamRunRecord[]
  listEntries: (workspaceId: string) => MemoryEntryWithSources[]
  logError?: (workspaceId: string, error: unknown) => void
  now?: () => number
}): TeamMemoryExportService => {
  const timers = new Map<string, ReturnType<typeof setTimeout>>()
  const pending = new Set<string>()

  const cancel = (workspaceId: string) => {
    const timer = timers.get(workspaceId)
    if (timer) clearTimeout(timer)
    timers.delete(workspaceId)
    pending.delete(workspaceId)
  }

  const flush = async (workspaceId: string) => {
    const timer = timers.get(workspaceId)
    if (timer) clearTimeout(timer)
    timers.delete(workspaceId)
    const wasPending = pending.has(workspaceId)
    let workspacePath: string
    try {
      workspacePath = getWorkspacePath(workspaceId)
    } catch {
      pending.delete(workspaceId)
      return
    }
    if (!existsSync(workspacePath)) {
      pending.delete(workspaceId)
      return
    }
    const targetPath = getMemoryFilePath(workspacePath)
    try {
      mkdirSync(dirname(targetPath), { recursive: true })
      backupExistingIfNeeded(targetPath, now)
      writeUtf8FileAtomically(
        targetPath,
        renderMemoryExport(listEntries(workspaceId), listDreamRuns(workspaceId))
      )
      pending.delete(workspaceId)
    } catch (error) {
      if (wasPending) pending.add(workspaceId)
      throw error
    }
  }

  return {
    cancel,
    async close() {
      const workspaceIds = [...pending]
      for (const workspaceId of workspaceIds) {
        try {
          await flush(workspaceId)
        } catch (error) {
          logError(workspaceId, error)
        }
      }
      for (const workspaceId of [...timers.keys()]) cancel(workspaceId)
    },
    flush,
    schedule(workspaceId: string) {
      const existing = timers.get(workspaceId)
      if (existing) clearTimeout(existing)
      pending.add(workspaceId)
      const timer = setTimeout(() => {
        void flush(workspaceId).catch((error) => logError(workspaceId, error))
      }, debounceMs)
      timer.unref?.()
      timers.set(workspaceId, timer)
    },
  }
}
