// GENERATED by `node gateway/scripts/ship-bundle.mjs --bake`. DO NOT edit by hand.
//
// Plan B (no R2): the worker ships the real mobile-bundle BYTES in-process. ship --bake writes the
// version's JS/CSS files here as base64; bundles.ts decodes them at module load and serves the
// CURRENT_VERSION from memory, re-verified against the worker-anchored manifest (the SRI trust root).
// The DEFAULT is empty — with no baked bytes the serve route falls through to the v0 placeholder, so
// the existing gateway tests + local dev are unchanged until a real bundle is baked + deployed.
//
// COMMITTED as the empty default (a deploy regenerates the real bytes transiently; the multi-MB
// base64 of a real build is never committed — CI regenerates it before `wrangler deploy`). Each value:
// { b64: base64(file bytes), contentType }, keyed by the /assets/<version>/<path> URL the loader
// references and the serve route re-verifies. Only the manifest's JS/CSS are baked.
export const GENERATED_BUNDLE_ASSETS: Readonly<
  Record<string, { readonly b64: string; readonly contentType: string }>
> = {}
