// @generated by gateway/scripts/ship-bundle.mjs — DO NOT EDIT BY HAND.
//
// The WORKER-ANCHORED bundle manifest: the sha384 trust root for one release version. This file
// is baked into the worker by `wrangler deploy`; the serve route (src/bundles.ts) re-verifies
// every byte read from R2 against these pins (502 on mismatch) and the /app loader emits browser
// SRI ONLY for the `isEntry` chunks. The manifest is NEVER read from R2 — a compromised R2 that
// serves different bytes than these pins loses at the serve-time re-verify.
//
// To re-ship: build web/dist, then run
//   node gateway/scripts/ship-bundle.mjs --dist web/dist --version <v>
// which overwrites this file, after which `wrangler deploy` ships the new manifest.
//
// COMMITTED (not gitignored) on purpose: the worker imports it, so it must exist for typecheck +
// `wrangler deploy` even on a fresh checkout; and committing it makes the anchored sha384 set an
// auditable, diffable part of each release (a manifest change shows up in code review). The
// committed default is the test-current manifest so local dev / the test suite have a real module
// to import; CI regenerates it per release before `wrangler deploy`. The gateway falls back to the
// in-worker placeholder (src/bundles.ts) when R2 is unbound or the requested version != this one.
//
// `kind`/`url`/`integrity` are the same fields the serve route re-verifies; `isEntry` marks the
// chunks the /app loader emits with browser SRI (entry js + its css). Lazy chunks (isEntry:false)
// are NOT in the loader — they are fetched on demand and protected only by the serve-time
// re-verify against these same pins. src/bundles.ts BundleManifestEntry carries `isEntry?`.

import type { BundleManifest } from './bundles.js'

export const GENERATED_BUNDLE_VERSION = '1.7.0' as const

export const GENERATED_BUNDLE_MANIFEST: BundleManifest = {
  version: '1.7.0',
  entries: [
    {
      kind: 'script',
      url: '/assets/1.7.0/index-AbCd1234.js',
      integrity: 'sha384-vGTnjnfq9pji5olK6wdM4OldwVb62Yb5EQhtns5zPq8vE37VBzwkOUbKVVJgxebj',
      isEntry: true,
    },
    {
      kind: 'style',
      url: '/assets/1.7.0/index-EfGh5678.css',
      integrity: 'sha384-M9ylRDLCwz8liyVwJ+cRuVxZk6vWF9Sl2qyrDJmhIhPNqQuYouEYzjhP384Ux3w4',
      isEntry: true,
    },
    {
      kind: 'script',
      url: '/assets/1.7.0/vendor-Zz0099Xx.js',
      integrity: 'sha384-khPz+zP9Hq5fJbkbqqzK32YrTsS+L36nEuedg+SfR0KFgqFeo6JMBTu+OQPqXeBo',
      isEntry: false,
    },
  ],
}
